### ISSUE TITLE
Server Locked when closing without connection

### ISSUE THREAD

**Issue by JuanBohorquez3** [QuantumQuadrate/Instrument_Servers#25]
Entering "q" to quit the server locks it (only way to close it or otherwise interact with it is to close the command line) in the following cases:
- Only the analog output device line have been left uncommented. All
- Keylistener has been started but connection has not been established
- Connection to server has been opened, then closed.
Looks like the server doesn't like to quit when there is no established connection.

Last message printed to terminal (logger.info etc) is of the following form:
> The following devices will be stopped: [<analogout.AnalogOutput object at 0x10FB0220>]

or a warning about improper closing of the AO task.

A similar issue arises when closing with the HSDIO initialized

**Comment by prhuft** [comment]
This arises from the blocking behavior of the socket.accept() call in tcp.py. A hacky solution would be to establish a local connection when 'q' is hit, so the server essentially connects to itself, the accept call finishes, and the server quits.
