### ISSUE TITLE
Logging level debug doesn't log debug statements

### ISSUE THREAD

**Issue by prhuft** [QuantumQuadrate/Instrument_Servers#26]
Applies to Instruments and the PXI class: the root logging level is set to logging.DEBUG, yet logging.debug("my message") statements are not logged to the console. Debug level statements are still not logged when setting the level to logging.NOTSET, which should log statements of all levels to the console, which would imply the setLevel call is being overwritten somehow or ignored.

**Comment by c-poole** [comment]
Preston and I had an offline conversation about this: The issue was that both the root logger and its handler need to have the logging level set to DEBUG or else the logs would be filtered.
