### ISSUE TITLE
Slow cycle when not cycling continuously

### ISSUE THREAD

**Issue by JuanBohorquez3** [QuantumQuadrate/Instrument_Servers#36]
The rate at which the server performs a measurement cycle, parses the data, then sends it back to cspy is roughly one third what it should be. 

The HSDIO cycles at the correct rate but the data isn't sent back at that rate. Issue seems ubiquitous.

**Comment by prhuft** [comment]
this is still an issue in Rb because we run experiments differently than the other experiments. namely, we uncheck "cycle continuously" in CsPy PXI comm. when we run experiments. If this is checked, the cycle time is fast, but if unchecked the cycle time is about twice as slow.

**Comment by prhuft** [comment]
This issue is reproduceable in both Rb and Hybrid.
